<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Harry-PC" ignored="3" name="Default test(failed)" tests="2" failures="2" timestamp="20 Nov 2020 05:53:20 GMT" time="0.089" errors="0">
  <testcase name="myName4" time="0.017" classname="testPackage.FailedTestCaseExample2">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testPackage.FailedTestCaseExample2.myName4(FailedTestCaseExample2.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- myName4 -->
  <testcase name="myName2" time="0.015" classname="testPackage.FailedTestCaseExample2">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testPackage.FailedTestCaseExample2.myName2(FailedTestCaseExample2.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- myName2 -->
  <testcase name="myName3" time="0.0" classname="testPackage.FailedTestCaseExample2">
    <ignored/>
  </testcase> <!-- myName3 -->
  <testcase name="myName1" time="0.0" classname="testPackage.FailedTestCaseExample2">
    <ignored/>
  </testcase> <!-- myName1 -->
  <testcase name="myName0" time="0.0" classname="testPackage.FailedTestCaseExample2">
    <ignored/>
  </testcase> <!-- myName0 -->
</testsuite> <!-- Default test(failed) -->
